### ISSUE TITLE
header

### ISSUE THREAD

**Issue by jlangkau** [industrial-data-space/idscp2-jvm#5]
https://github.com/industrial-data-space/idscp2-java/blob/c98917b6a3e8e6aa0583d1a1c009dba86a96546c/idscp2-app-layer/src/main/proto/idscp2-app.proto#L21

...a little more exrpessive:

```protobuf

message FuaHeader {
    string name = 1;
    string value = 2;
}

message FuaMessage {
    repeated FuaHeader header = 1;
    bytes payload = 2;
}

```

**Comment by milux** [comment]
This has been done quite a while ago, recent versions since at least 0.8.0 have a new message type with that functionality.
Can also be utilized via new parameters of the Apache Camel component, although not documented yet.
