### ISSUE TITLE
Improve the Wiki by Adding an Overview Page

### ISSUE THREAD

**Issue by MatthiasGr** [industrial-data-space/idscp2-jvm#8]
When I tried to understand the IDSCP2 protocol, I found the documentation to be a bit overwhelming at first.
To hopefully make it a bit simpler to get started with the documentation, I have added an overview page to serve as an introduction.

The page summarizes the core functionality of each component in the protocol and links to the appropriate section in the documentation for further reading.
It also contains a diagram showing a successful IDSCP2 handshake without any re-authentication or DAT refresh.

Since GitHub does not seem to support pull requests against a repository's wiki, I am submitting my patches as an issue.
The changes can be found [here](https://github.com/MatthiasGr/idscp2-jvm-wiki).

Feel free to let me know if I got something incorrect or you want me to make changes.

**Comment by morbitzer** [comment]
Added. Thanks for your input.
